# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_auto_20171121_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer_title',
            new_name='answer_text',
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
